runtime: nodejs16

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /health
    script: auto
    secure: optional

  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always

network:
  forwarded_ports:
    - 8080

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10